properly wipe invocation files

diff --git a/main/src/main/resources/templates/bin/stool-function b/main/src/main/resources/templates/bin/stool-function
--- a/main/src/main/resources/templates/bin/stool-function
+++ b/main/src/main/resources/templates/bin/stool-function
@@ -60,7 +60,7 @@ stool() {
     if [ -f $STOOL_INVOCATION ] ; then
       . $STOOL_INVOCATION
       # I've seen an empty $USER when running stool from a cron jobs
-      mv -f $STOOL_INVOCATION $bin/lib/run/users/$USER || echo 'cannot move invocation file, $USER variable not set?'
+      mv -f $STOOL_INVOCATION $bin/lib/run/users/$USER || (echo 'cannot move invocation file, $USER variable not set?'; rm $STOOL_INVOCATION)
     fi
   fi
 
