renamed invocation option to shell

diff --git a/main/src/main/resources/templates/bin/stool-function b/main/src/main/resources/templates/bin/stool-function
--- a/main/src/main/resources/templates/bin/stool-function
+++ b/main/src/main/resources/templates/bin/stool-function
@@ -1,16 +1,16 @@
 # Stool shell functions for bash
 # Source this file in your ~/.bashrc
 
-export STOOL_INVOCATION=${{stool.bin}}/lib/run/users/.stool-invocation-$$-$(date +%N)
+export STOOL_SHELL_FILE=${{stool.bin}}/lib/run/users/.stool-shell-file-$$-$(date +%N)
 ${{man.path}}
 
 stool() {
   if [ "$1" = "-service" ] ; then
-    # don't use invocation file because PS1 would be empty and USER is undefined
+    # don't use shell file file because PS1 would be empty and USER is undefined
     local interactiveArgs=""
     shift
   else
-    local interactiveArgs="-invocation $STOOL_INVOCATION"
+    local interactiveArgs="-shell $STOOL_SHELL_FILE"
   fi
 
   # Special variable handling: they are private and you cannot export them on Mac OS.
@@ -64,10 +64,10 @@ stool() {
     done
     STOOL_BIN=$bin $java $STOOL_OPTS -cp $cp net.oneandone.stool.Main $interactiveArgs "$@"
     result=$?
-    if [ -f $STOOL_INVOCATION ] ; then
-      . $STOOL_INVOCATION
+    if [ -f $STOOL_SHELL_FILE ] ; then
+      . $STOOL_SHELL_FILE
       # I've seen an empty $USER when running stool from a cron jobs
-      mv -f $STOOL_INVOCATION $bin/lib/run/users/$USER || (echo "cannot move invocation file, check USER variable: $USER"; rm $STOOL_INVOCATION)
+      mv -f $STOOL_SHELL_FILE $bin/lib/run/users/$USER || (echo "cannot move shell file, check USER variable: $USER"; rm $STOOL_INVOCATION)
     fi
   fi
 
