replaced stool-raw.sh by a normal stool application file

diff --git a/main/src/main/resources/templates/bin/stool-function b/main/src/main/resources/templates/bin/stool-function
--- a/main/src/main/resources/templates/bin/stool-function
+++ b/main/src/main/resources/templates/bin/stool-function
@@ -67,7 +67,7 @@ stool() {
     if [ -f $STOOL_SHELL_FILE ] ; then
       . $STOOL_SHELL_FILE
       # I've seen an empty $USER when running stool from a cron jobs
-      mv -f $STOOL_SHELL_FILE $bin/lib/run/users/$USER || (echo "cannot move shell file, check USER variable: $USER"; rm $STOOL_INVOCATION)
+      mv -f $STOOL_SHELL_FILE $bin/lib/run/users/$USER || (echo "cannot move shell file, check USER variable: $USER"; rm $STOOL_SHELL_FILE)
     fi
   fi
 
